### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by Besleh** [Murdy007/Wizzy#6] opened 2016-05-09 10:15 UTC
game keeps crashing all he time  both with and without fastcraft
and with and without biomes

**Comment by Murdy007** [comment] 2016-05-13 01:36
Can you please post a crash report, tell me your Wizzy version number, and if you are running 64 bit or 32 bit Java.

**Comment by Besleh** [comment] 2016-05-16 13:37
http://pastebin.com/1twGpGZ5

**Comment by Murdy007** [comment] 2016-05-29 00:54
I have narrowed down the issue to what may be causing it. Are you using Standard Wizzy (selected when you installed the modpack) with no other or custom mods installed?

**Comment by Besleh** [comment] 2016-05-29 12:08
i use all mods   i can check not added any myself

**Comment by Murdy007** [comment] 2016-06-07 04:19
Thankyou for telling me this problem. We have found out that the problem is most likely the OreSpawn mod. Please disable it through the atlauncher instances page and then tell us if the issue occurs again.

    On Monday, 30 May 2016 12:08 AM, Besleh <notifications@github.com> wrote:
 

 i use all mods i can check not added any myself—

**Comment by Murdy007** [comment] 2016-07-26 06:00
Orespawn has been removed from Wizzy until this issue is fixed by the developer. Issue is now closed.

**Closed by Murdy007** 2016-07-26 06:00 UTC
